
services:
  krusch_memory_db:
    image: ankane/pgvector:latest
    container_name: krusch_memory_pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: krusch_memory
    ports:
      - "5441:5432"
    volumes:
      - krusch_memory_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

volumes:
  krusch_memory_data:
